const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',

  ADD_WISHITEM_SUCCESS: 'ADD_WISHITEM_SUCCESS',
  ADD_WISHITEM_FAILURE: 'ADD_WISHITEM_FAILURE',

  WISHLIST_ITEMS_STATE_CHANGE: 'WISHLIST_ITEMS_STATE_CHANGE',

  /*REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  SET_CART_FROM_FIREBASE: "SET_CART_FROM_FIREBASE",
  UPDATE_CART_IN_FIREBASE: "UPDATE_CART_IN_FIREBASE",*/
};

export default CartActionTypes;
