//Data normalisation, using Hash Tables
const Specialist_Data = {
  cardiologist: {
    //UrlParameter same as the title
    id: 1,
    title: 'Cardiologist',
    routeName: 'cardiologist',
    items: [
      {
        id: 1,
        title: 'Dr XYZ1',
        speciality: 'Cardiologist',
        Years_Experience: 5,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Harare',
        Virtual_Appointment: 0,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 0,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: -17.849961,
          lng: 31.077799,
        },
      },
      {
        id: 2,
        title: 'Dr XYZ2',
        speciality: 'Cardiologist',
        Years_Experience: 7,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Harare',
        Virtual_Appointment: 1,
        Physical_Appointment: 0,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 13,
        Physical_Appointment_Fee: 0,
        HomeVisit_Appointment_Fee: 45,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: -17.841791,
          lng: 30.979952,
        },
      },
      {
        id: 3,
        title: 'Dr AYZ3',
        speciality: 'Cardiologist',
        Years_Experience: 9,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Gweru',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 0,
        Virtual_Appointment_Fee: 14,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 0,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: -19.460428,
          lng: 29.793763,
        },
      },
      {
        id: 4,
        title: 'Dr XTJ',
        speciality: 'Cardiologist',
        Years_Experience: 12,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Harare',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 27,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 62,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: -17.848001,
          lng: 31.089815,
        },
      },
      {
        id: 5,
        title: 'Dr XTJ2',
        speciality: 'Cardiologist',
        Years_Experience: 8,
        Practice_Name: 'TKZ',
        Practice_Code: '123AHT',
        Location: 'Bulawayo',
        Virtual_Appointment: 1,
        Physical_Appointment: 0,
        HomeVisit_Appointment: 0,
        Virtual_Appointment_Fee: 12.5,
        Physical_Appointment_Fee: 0,
        HomeVisit_Appointment_Fee: 0,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: -20.191577,
          lng: 28.607481,
        },
      },
      {
        id: 6,
        title: 'Dr XTJX',
        Years_Experience: 5,
        speciality: 'Cardiologist',
        Practice_Name: 'TKZ',
        Practice_Code: '123AHT',
        Location: 'Bulawayo',
        Virtual_Appointment: 1,
        Physical_Appointment: 0,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 17,
        Physical_Appointment_Fee: 0,
        HomeVisit_Appointment_Fee: 48,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: -20.132276,
          lng: 28.578985,
        },
      },
      {
        id: 7,
        title: 'Dr CXTJ',
        speciality: 'Cardiologist',
        Years_Experience: 11,
        Practice_Name: 'TKZ',
        Practice_Code: '123AHT',
        Location: 'Masvingo',
        Virtual_Appointment: 0,
        Physical_Appointment: 0,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 0,
        Physical_Appointment_Fee: 0,
        HomeVisit_Appointment_Fee: 35,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: -20.077134,
          lng: 30.834545,
        },
      },
    ],
  },
  obstetrician: {
    id: 2,
    title: 'Obstetrician',
    routeName: 'obstetrician',
    items: [
      {
        id: 1,
        title: 'Dr XYZ',
        Years_Experience: 10,
        speciality: 'Obstetrician',
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 18,
        Physical_Appointment_Fee: 24,
        HomeVisit_Appointment_Fee: 52,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 2,
        title: 'Dr XYZ',
        speciality: 'Obstetrician',
        Years_Experience: 10,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 0,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 0,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 3,
        title: 'Dr AYZ',
        speciality: 'Obstetrician',
        Years_Experience: 9,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 0,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 0,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 4,
        title: 'Dr XTJ',
        speciality: 'Obstetrician',
        Years_Experience: 10,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 0,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 5,
        title: 'Dr XTJ',
        speciality: 'Obstetrician',
        Years_Experience: 10,
        Practice_Name: 'TKZ',
        Practice_Code: '123AHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 0,
        Virtual_Appointment_Fee: 0,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 0,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
    ],
  },
  optometrist: {
    id: 3,
    title: 'Optometrist',
    routeName: 'optometrist',
    items: [
      {
        id: 1,
        title: 'Dr XYZ',
        speciality: 'Optometrist',
        Years_Experience: 10,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 0,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 0,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 2,
        title: 'Dr XYZ',
        speciality: 'Optometrist',
        Years_Experience: 10,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 0,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 0,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 3,
        title: 'Dr AYZ',
        speciality: 'Optometrist',
        Years_Experience: 9,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 0,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 0,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 4,
        title: 'Dr XTJ',
        speciality: 'Optometrist',
        Years_Experience: 10,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 0,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 0,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 5,
        title: 'Dr XTJ',
        speciality: 'Optometrist',
        Years_Experience: 10,
        Practice_Name: 'TKZ',
        Practice_Code: '123AHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.2465623,
          lng: -79.874578,
        },
      },
      {
        id: 6,
        title: 'Dr XYZ',
        speciality: 'Optometrist',
        Years_Experience: 10,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
    ],
  },
  occupational_therapist: {
    id: 4,
    title: 'Occupational Therapist',
    routeName: 'occupational_therapist',
    items: [
      {
        id: 1,
        title: 'Dr XYZ',
        speciality: 'Occupational Therapist',
        Years_Experience: 10,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 2,
        title: 'Dr XYZ',
        speciality: 'Occupational Therapist',
        Years_Experience: 10,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 3,
        title: 'Dr AYZ',
        speciality: 'Occupational Therapist',
        Years_Experience: 9,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 4,
        title: 'Dr XTJ',
        speciality: 'Occupational Therapist',
        Years_Experience: 10,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 5,
        title: 'Dr XTJ',
        speciality: 'Occupational Therapist',
        Years_Experience: 10,
        Practice_Name: 'TKZ',
        Practice_Code: '123AHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 6,
        title: 'Dr XTJ',
        speciality: 'Occupational Therapist',
        Years_Experience: 10,
        Practice_Name: 'TKZ',
        Practice_Code: '123AHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
    ],
  },
  gynecologist: {
    id: 5,
    title: 'Gynecologist',
    routeName: 'gynecologist',
    items: [
      {
        id: 1,
        title: 'Dr XYZ',
        speciality: 'Gynecologist',
        Years_Experience: 10,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 2,
        title: 'Dr XYZ',
        speciality: 'Gynecologist',
        Years_Experience: 10,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 3,
        title: 'Dr AYZ',
        speciality: 'Gynecologist',
        Years_Experience: 9,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 4,
        title: 'Dr XTJ',
        speciality: 'Gynecologist',
        Years_Experience: 10,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 5,
        title: 'Dr XTJ',
        speciality: 'Gynecologist',
        Years_Experience: 10,
        Practice_Name: 'TKZ',
        Practice_Code: '123AHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
    ],
  },
  orthopaedist: {
    id: 6,
    title: 'Orthopaedist',
    routeName: 'orthopaedist',
    items: [
      {
        id: 1,
        title: 'Dr XYZ',
        speciality: 'Orthopaedist',
        Years_Experience: 10,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 2,
        title: 'Dr XYZ',
        speciality: 'Orthopaedist',
        Years_Experience: 10,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 3,
        title: 'Dr AYZ',
        speciality: 'Orthopaedist',
        Years_Experience: 9,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 4,
        title: 'Dr XTJ',
        speciality: 'Orthopaedist',
        Years_Experience: 10,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 5,
        title: 'Dr XTJ',
        speciality: 'Orthopaedist',
        Years_Experience: 10,
        Practice_Name: 'TKZ',
        Practice_Code: '123AHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 6,
        title: 'Dr XTJ',
        speciality: 'Orthopaedist',
        Years_Experience: 10,
        Practice_Name: 'TKZ',
        Practice_Code: '123AHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
    ],
  },
  general_doctor: {
    id: 7,
    title: 'General Doctor',
    routeName: 'general_doctor',
    items: [
      {
        id: 1,
        title: 'Dr XYZ',
        speciality: 'General Doctor',
        Years_Experience: 10,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 2,
        title: 'Dr XYZ',
        speciality: 'General Doctor',
        Years_Experience: 10,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 4,
        title: 'Dr XTJ',
        speciality: 'General Doctor',
        Years_Experience: 10,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 5,
        title: 'Dr XTJ',
        speciality: 'General Doctor',
        Years_Experience: 10,
        Practice_Name: 'TKZ',
        Practice_Code: '123AHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 6,
        title: 'Dr XTJ',
        speciality: 'General Doctor',
        Years_Experience: 10,
        Practice_Name: 'TKZ',
        Practice_Code: '123AHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
    ],
  },
  dermatologists: {
    id: 8,
    title: 'Dermatologists',
    routeName: 'dermatologists',
    items: [
      {
        id: 1,
        title: 'Dr XYZ',
        speciality: 'Dermatologists',
        Years_Experience: 10,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 2,
        title: 'Dr XYZ',
        speciality: 'Dermatologists',
        Years_Experience: 10,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 3,
        title: 'Dr AYZ',
        speciality: 'Dermatologists',
        Years_Experience: 9,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 4,
        title: 'Dr XTJ',
        speciality: 'Dermatologists',
        Years_Experience: 10,
        Practice_Name: 'XYZ',
        Practice_Code: '123DHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 5,
        title: 'Dr XTJ',
        speciality: 'Dermatologists',
        Years_Experience: 10,
        Practice_Name: 'TKZ',
        Practice_Code: '123AHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
      {
        id: 6,
        title: 'Dr XTJ',
        speciality: 'Dermatologists',
        Years_Experience: 10,
        Practice_Name: 'TKZ',
        Practice_Code: '123AHT',
        Location: 'Eastlie',
        Virtual_Appointment: 1,
        Physical_Appointment: 1,
        HomeVisit_Appointment: 1,
        Virtual_Appointment_Fee: 10,
        Physical_Appointment_Fee: 25,
        HomeVisit_Appointment_Fee: 50,
        image: require('../assets/imgs/Surgeon1.jpg'),
        geometry: {
          lat: 43.6465623,
          lng: -79.374578,
        },
      },
    ],
  },
};

export default Specialist_Data;
