export const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

  USER_STATE_CHANGE: 'USER_STATE_CHANGE',
  USER_PROFILE_IMAGE_STATE_CHANGE: 'USER_PROFILE_IMAGE_STATE_CHANGE',

  USER_TOGGLE_ADDRECORD: 'USER_TOGGLE_ADDRECORD',
  USER_VIEW_MAP: 'USER_VIEW_MAP',

  USER_RECORDS_STATE_CHANGE: 'USER_RECORDS_STATE_CHANGE',
  USER_DIGITALRECORDS_STATE_CHANGE: 'USER_DIGITALRECORDS_STATE_CHANGE',
  USER_DIGITALRECORDS_STATE_CHANGE2: 'USER_DIGITALRECORDS_STATE_CHANGE2',

  ADD_MEDICAL_RECORD: 'ADD_MEDICAL_RECORD',
  ADD_MEDICAL_RECORD_FAILER: 'ADD_MEDICAL_RECORD_FAILER',
  REMOVE_MEDICAL_RECORD: 'REMOVE_MEDICAL_RECORD',
  REMOVE_MEDICAL_RECORD_FAILER: 'REMOVE_MEDICAL_RECORD_FAILER',

  SEARCH_SPECIALIST: 'SEARCH_SPECIALIST',
  SPECIALIST_LOCATION: 'SPECIALIST_LOCATION',
  HEADER_TAB_OPTION_CHANGE: 'HEADER_TAB_OPTION_CHANGE',
  DEPENDANT_SELECTION: 'DEPENDANT_SELECTION',

  USER_APPOINTMENTS_STATE_CHANGE: 'USER_APPOINTMENTS_STATE_CHANGE',
  ADD_APPOINTMENT_RECORD: 'ADD_APPOINTMENT_RECORD',
  ADD_APPOINTMENT_RECORD_FAILER: 'ADD_APPOINTMENT_RECORD_FAILER',

  USER_DEPENDANTS_STATE_CHANGE: 'USER_DEPENDANTS_STATE_CHANGE',
  USER_DEPENDANTS_STATE_CHANGE_FAILER: 'USER_DEPENDANTS_STATE_CHANGE_FAILER',
  ADD_DEPENDANT_RECORD: 'ADD_DEPENDANT_RECORD',
  ADD_DEPENDANT_RECORD_FAILER: 'ADD_DEPENDANT_RECORD_FAILER',
  REMOVE_DEPENDANT: 'REMOVE_DEPENDANT',
  REMOVE_DEPENDANT_FAILER: 'REMOVE_DEPENDANT_FAILER',
};
